Merge client-sessions into main
InstantDomain/instant-bandit pull request #14
Opened 2022-06-02 21:18 UTC by jasonscharf

This PR integrates session handling with the InstantBandit component and handles `localStorage` quota errors. Sessions hold the experiments and variants seen in sites, and a session ID is attached with initialization requests when present.

2022-06-02 21:18 UTC, jasonscharf commented
Current dependencies on/for this PR:
* main
  * **PR #14** <a href="https://app.graphite.dev/github/pr/InstantDomain/instant-bandit/14" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/InstantDomain/instant-bandit/14?utm_source=stack-comment).

2022-06-03 15:50 UTC, hartshorne requested changes
will https://nextjs.org/docs/testing#setting-up-jest-with-the-rust-compiler be useful, or maybe too specific to next?

2022-06-03 15:50 UTC, hartshorne commented on lib/providers/session.ts
> +        // IE 8
no need to support or even think about IE 8 anymore

2022-06-03 20:03 UTC, hartshorne approved these changes

2022-06-07 22:50 UTC, hartshorne approved these changes

2022-06-08 20:16 UTC, merged