Add documentation
InstantDomain/instant-bandit pull request #55
Opened 2022-09-12 15:51 UTC by jasonscharf

Adds comprehensive documentation around setup and usage.

2022-09-12 15:56 UTC, jasonscharf commented
Notes:

- Best way to consume this PR, since it's primarily just a bunch of new content, is probably to navigate the branch and click through the Markdown links.

- I put the docs in /pages because I've got a follow up PR that allows the docs to be hosted live somewhere + syntax highlighting via next-mdx.

2022-09-12 16:59 UTC, tbakerx commented
Hey @jasonscharf thanks for putting this together! Going through it now!

2022-09-12 18:51 UTC, tbakerx requested changes
This is looking good! Thanks for putting this all together, should definitely help any new-comers to the repo get up and running. It does seem like there's a fair amount of duplication in the guides (setup/usage explained in several spots) however, more docs > less docs.

I've left a series of minor comments on just spelling/grammar stuff mostly. Have a look and then ping me and we can get er merged and released. Thanks again dude!

2022-09-12 18:51 UTC, tbakerx commented on pages/docs/internals/how-it-works.md
> +```json
Should include `"inactive": true`?

2022-09-12 18:51 UTC, tbakerx commented on pages/docs/internals/how-it-works.md
> +You can leave it in the site configuration as a historical
Seems to trail off, should say something along the lines of "to maintain a history"?

2022-09-12 18:51 UTC, tbakerx commented on pages/docs/setup/with-nextjs.md
> + <InstantBandit {...serverSideProps}>...</InstantBandit>
We should probably include the `Graceful Shutdown` nextjs-specific docs here in this setup?

2022-09-14 16:00 UTC, jasonscharf commented
@tbakerx You rock! Thanks so much for reviewing. I feel you on the duplication thing, it's a docs thing I've picked up over the years from tech writers and other examples (probably from reading too much docs lol). I might chop it down and bit, but I'll address the other items first. Thanks again!

2022-10-13 15:49 UTC, jasonscharf commented
Hey @tbakerx , made some spot fixes based on your feedback. Let me know if I missed anything!

As for deduping some of the setup stuff, I'm going to hold off for now, unless you think it should be addressed in this PR. I'd like to remove the server setup steps entirely for the majority of users so only self-hosters need them. Beau gave me an idea there :)

2022-10-18 17:13 UTC, merged